

services:
  # üõ´ Backend .NET API
  api:
    build:
      context: .
      dockerfile: Sisand.Airlines.Api/Dockerfile
    ports:
      - "5300:8080"
    depends_on:
      - postgres
      - mailhog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=sisanddb;Username=postgres;Password=123456
    networks:
      - sisand_network

  # üé® Frontend Angular
  # frontend:
  #   build:
  #     context: ./sisand-airlines-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:80"
  #   depends_on:
  #     - api
  #   networks:
  #     - sisand_network

  # üêò Banco de Dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres-sisand
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sisanddb
    ports:
      - "5432:5432"
    volumes:
      - ./init_v1.1.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sisand_network

  # üì¨ Mailhog (para e-mails de confirma√ß√£o)
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - sisand_network

networks:
  sisand_network:
    driver: bridge
